app:
  port: "8080"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "pass"
  dbname: "mydb"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m